import type { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import SiteHeader from '@/components/site-header'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  const className = cn(
    'min-h-screen bg-background font-sans antialiased',
    inter.variable,
  )

  return (
    <html lang="en">
      <body className={className}>
        <div className="relative flex flex-col min-h-dvh bg-background">
          <SiteHeader />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  )
}
export default RootLayout
